version: '3.3'

services:
  app:
    build: .
    container_name: fastapi-server
    command: uvicorn todo-app.app:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
    volumes:
      - .:/code
